adminUser: admin
adminPassword: ""

service:
  type: NodePort
  nodePort: 32030

persistence:
  enabled: true
  storageClassName: local-path
  size: 5Gi

initChownData:
  enabled: false

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://192.168.1.50:9090
        isDefault: true
      - name: Loki
        type: loki
        access: proxy
        url: http://loki.observability.svc.cluster.local:3100
