replicaCount: 1
revisionHistoryLimit: 3

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "traefik"
  annotations:
    cert-manager.io/cluster-issuer: "lab-selfsigned"
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
  hosts:
    - host: wikijs.192.168.1.80.sslip.io
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: wikijs-tls
      hosts:
        - wikijs.192.168.1.80.sslip.io

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 1Gi

nodeSelector:
  kubernetes.io/hostname: oma01rpicls01mstr01

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL

postgresql:
  enabled: false

externalPostgresql:
  host: "192.168.1.216"
  port: "5432"
  database: "wikijs"
  username: "wikijs"
  existingSecret: "wikijs-db-secret"
  existingSecretKey: "db-password"
  ssl: "false"
