service:
  type: NodePort
  nodePort: 32093

opencost:
  exporter:
    defaultClusterId: raspi-lab
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 300m
        memory: 512Mi
  ui:
    enabled: true
    resources:
      requests:
        cpu: 25m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 256Mi
  prometheus:
    internal:
      enabled: false
      serviceName: prometheus-server
      namespaceName: observability
      port: 80
      scheme: http
    external:
      enabled: true
      url: http://192.168.1.50:9090
