apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-image-updater-registry-pull
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-image-updater
    app.kubernetes.io/part-of: argocd-image-updater
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-store
  target:
    name: argocd-image-updater-registry-pull
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {"auths":{"192.168.1.15:5000":{"username":"{{ .username }}","password":"{{ .password }}","auth":"{{ printf "%s:%s" .username .password | b64enc }}"}}}
  data:
    - secretKey: username
      remoteRef:
        key: homelab/registry/lab-registry01
        property: registry_user
    - secretKey: password
      remoteRef:
        key: homelab/registry/lab-registry01
        property: registry_password
