apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bs01-pki
  namespace: argocd
  labels:
    app.kubernetes.io/name: bs01-pki
    app.kubernetes.io/part-of: bs01-field-cluster
    droneops.io/deployment-profile: bs01-field
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  source:
    repoURL: https://github.com/ajh-lab/lab.git
    targetRevision: main
    path: k8s/field/bs01/pki
    directory:
      recurse: false
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
    syncOptions:
      - ServerSideApply=true
      - PruneLast=true

