apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  ai-workstation-evox2.server: |
    ai-workstation-evox2:53 {
        hosts {
            192.168.1.123 ai-workstation-evox2
            fallthrough
        }
    }
